import "./globals.css";
import { HeaderProvider } from "@/context/HeaderContext";
import DisableRightClick from "@/component/DisableRightClick";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <HeaderProvider>
      <html>
        <body>
          <DisableRightClick />
          {children}
        </body>
      </html>
    </HeaderProvider>
  );
}
