import { Geist, Geist_Mono } from 'next/font/google'
// import { Toaster } from "react-hot-toast";

import './globals.css'

import { HeaderProvider } from '@/context/HeaderContext'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <HeaderProvider>
      <html lang="en">
        <body>
        {/* <Toaster position="top-right" /> */}
          {children}
        </body>
      </html>
    </HeaderProvider>
  )
}
