import "./globals.css";
import DisableRightClick from "@/component/DisableRightClick";
import InitialLoadTracker from "@/component/initialLoadTracker/InitialLoadTracker";

import { HeaderProvider } from "@/context/HeaderContext";
import { RegisterProvider } from "@/context/registerContext/RegisterContext";
import { Toaster } from "@/component/customToast/CustomToast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <RegisterProvider>
      <html>
        <body>
          <HeaderProvider>
            <InitialLoadTracker />
            <DisableRightClick />

            {children}

            <Toaster position="top-right" />
          </HeaderProvider>
        </body>
      </html>
    </RegisterProvider>
  );
}
