import Header from "@/component/header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <div>
      <Header />
      {children}
    </div>
  );
}
